### PR TITLE
Adding support for compression

### PR DESCRIPTION
**Pull request by femueller**
This PR allows to utilize `bz2` and `deflate` (zlib) compression in order to reduce network traffic.

It already exists in the [Scalyr Python Agent](https://www.scalyr.com/help/scalyr-agent#compressing).

Signed-off-by: Felix Mueller <felix.mueller@zalando.de>

### CODE REVIEW

**Comment by imron** [comment]
Thanks for that, I'll look at this shortly.

**Comment by femueller** [comment]
Is there any update on this?

**Comment by weilliu** [comment]
@imron Could you help Felix merge his commit?

**Comment by femueller** [comment]
Thanks a lot! 🤘

**Pull request merged**
